name: run main.py

on:
  schedule:
    - cron: '* * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: |
          python main.py
          git config --local user.email "matteo2881@gmail.com"
          git config --local user.name "DarkAngel2881"
          git add output.csv
          git commit -m "Add output.csv"
      
      - name: upload CSV file artifact
        uses: actions/upload-artifact@v2
        with:
          name: outputcsv
          path: substitutions.csv


      - name: push the changes to the main branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          file: output.csv
          
